INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (0, '31', 'Haute-Garonne', 'Occitanie');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (1, '13', 'Bouches-du-Rhône', 'Provence-Alpes-Côte d''Azur');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (2, '33', 'Gironde', 'Nouvelle-Aquitaine');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (3, '38', 'Isère', 'Auvergne-Rhône-Alpes');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (4, '42', 'Loire', 'Auvergne-Rhône-Alpes');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (5, '22', 'Côtes-d''Armor', 'Bretagne');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (6, '66', 'Pyrénées-Orientales', 'Occitanie');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (7, '34', 'Hérault', 'Occitanie');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (8, '69', 'Rhône', 'Auvergne-Rhône-Alpes');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (9, '1', 'Ain', 'Auvergne-Rhône-Alpes');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (10, '86', 'Vienne', 'Nouvelle-Aquitaine');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (11, '85', 'Vendée', 'Pays de la Loire');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (12, '49', 'Maine-et-Loire', 'Pays de la Loire');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (13, '21', 'Côte-d''Or', 'Bourgogne-Franche-Comté');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (14, '81', 'Tarn', 'Occitanie');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (15, '64', 'Pyrénées-Atlantiques', 'Nouvelle-Aquitaine');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (16, '78', 'Yvelines', 'Île-de-France');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (17, '53', 'Mayenne', 'Pays de la Loire');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (18, '59', 'Nord', 'Hauts-de-France');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (19, '26', 'Drôme', 'Auvergne-Rhône-Alpes');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (20, '6', 'Alpes-Maritimes', 'Provence-Alpes-Côte d''Azur');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (21, '80', 'Somme', 'Hauts-de-France');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (22, '29', 'Finistère', 'Bretagne');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (23, '47', 'Lot-et-Garonne', 'Nouvelle-Aquitaine');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (24, '76', 'Seine-Maritime', 'Normandie');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (25, '46', 'Lot', 'Occitanie');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (26, '93', 'Seine-Saint-Denis', 'Île-de-France');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (27, '89', 'Yonne', 'Bourgogne-Franche-Comté');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (28, '75', 'Paris', 'Île-de-France');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (29, '11', 'Aude', 'Occitanie');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (30, '91', 'Essonne', 'Île-de-France');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (31, '73', 'Savoie', 'Auvergne-Rhône-Alpes');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (32, '56', 'Morbihan', 'Bretagne');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (33, '5', 'Hautes-Alpes', 'Provence-Alpes-Côte d''Azur');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (34, '65', 'Hautes-Pyrénées', 'Occitanie');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (35, '37', 'Indre-et-Loire', 'Centre-Val de Loire');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (36, '74', 'Haute-Savoie', 'Auvergne-Rhône-Alpes');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (37, '14', 'Calvados', 'Normandie');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (38, '40', 'Landes', 'Nouvelle-Aquitaine');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (39, '43', 'Haute-Loire', 'Auvergne-Rhône-Alpes');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (40, '35', 'Ille-et-Vilaine', 'Bretagne');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (41, '84', 'Vaucluse', 'Provence-Alpes-Côte d''Azur');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (42, '7', 'Ardèche', 'Auvergne-Rhône-Alpes');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (43, '62', 'Pas-de-Calais', 'Hauts-de-France');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (44, '54', 'Meurthe-et-Moselle', 'Grand Est');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (45, '61', 'Orne', 'Normandie');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (46, '2B', 'Haute-Corse', 'Corse');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (47, '60', 'Oise', 'Hauts-de-France');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (48, '30', 'Gard', 'Occitanie');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (49, '63', 'Puy-de-Dôme', 'Auvergne-Rhône-Alpes');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (50, '79', 'Deux-Sèvres', 'Nouvelle-Aquitaine');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (51, '3', 'Allier', 'Auvergne-Rhône-Alpes');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (52, '67', 'Bas-Rhin', 'Grand Est');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (53, '55', 'Meuse', 'Grand Est');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (54, '50', 'Manche', 'Normandie');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (55, '95', 'Val-d''Oise', 'Île-de-France');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (56, '44', 'Loire-Atlantique', 'Pays de la Loire');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (57, '71', 'Saône-et-Loire', 'Bourgogne-Franche-Comté');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (58, '8', 'Ardennes', 'Grand Est');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (59, '39', 'Jura', 'Bourgogne-Franche-Comté');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (60, '18', 'Cher', 'Centre-Val de Loire');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (61, '45', 'Loiret', 'Centre-Val de Loire');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (62, '92', 'Hauts-de-Seine', 'Île-de-France');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (63, '90', 'Territoire de Belfort', 'Bourgogne-Franche-Comté');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (64, '24', 'Dordogne', 'Nouvelle-Aquitaine');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (65, '72', 'Sarthe', 'Pays de la Loire');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (66, '52', 'Haute-Marne', 'Grand Est');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (67, '2', 'Aisne', 'Hauts-de-France');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (68, '15', 'Cantal', 'Auvergne-Rhône-Alpes');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (69, '94', 'Val-de-Marne', 'Île-de-France');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (70, '68', 'Haut-Rhin', 'Grand Est');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (71, '36', 'Indre', 'Centre-Val de Loire');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (72, '25', 'Doubs', 'Bourgogne-Franche-Comté');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (73, '58', 'Nièvre', 'Bourgogne-Franche-Comté');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (74, '83', 'Var', 'Provence-Alpes-Côte d''Azur');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (75, '19', 'Corrèze', 'Nouvelle-Aquitaine');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (76, '23', 'Creuse', 'Nouvelle-Aquitaine');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (77, '51', 'Marne', 'Grand Est');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (78, '2B', 'Corse-du-Sud', 'Corse');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (79, '27', 'Eure', 'Normandie');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (80, '77', 'Seine-et-Marne', 'Île-de-France');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (81, '12', 'Aveyron', 'Occitanie');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (82, '28', 'Eure-et-Loir', 'Centre-Val de Loire');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (83, '32', 'Gers', 'Occitanie');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (84, '976', 'Mayotte', 'Mayotte');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (85, '17', 'Charente-Maritime', 'Nouvelle-Aquitaine');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (86, '16', 'Charente', 'Nouvelle-Aquitaine');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (87, '70', 'Haute-Saône', 'Bourgogne-Franche-Comté');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (88, '4', 'Alpes-de-Haute-Provence', 'Provence-Alpes-Côte d''Azur');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (89, '10', 'Aube', 'Grand Est');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (90, '87', 'Haute-Vienne', 'Nouvelle-Aquitaine');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (91, '57', 'Moselle', 'Grand Est');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (92, '41', 'Loir-et-Cher', 'Centre-Val de Loire');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (93, '48', 'Lozère', 'Occitanie');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (94, '88', 'Vosges', 'Grand Est');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (95, '973', 'Guyane', 'Guyane');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (96, '974', 'La Réunion', 'La Réunion');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (97, '972', 'Martinique', 'Martinique');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (98, '971', 'Guadeloupe', 'Guadeloupe');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (99, '82', 'Tarn-et-Garonne', 'Occitanie');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (100, '988', 'Nouvelle-Calédonie', 'Nouvelle Calédonie');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (101, '987', 'Polynésie française', 'Polynésie française');
INSERT INTO departement (id_departement, num_departement, nom_departement, nom_region) VALUES (102, '9', 'Ariège', 'Occitanie');
