INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (0, 'MUSIQUES ACTUELLES', 'MUSIQUES TRADITIONNELLES ET DU MONDE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (1, 'TRANSDISCIPLINAIRE', 'TRANSDISCIPLINAIRE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (2, 'PLURIDISCIPLINAIRE SPECTACLE VIVANT', 'PLURIDISCIPLINAIRE SPECTACLE VIVANT');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (3, 'MUSIQUES ACTUELLES', 'MUSIQUES AMPLIFIÉES OU ÉLECTRONIQUES');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (4, 'CIRQUE ET ARTS DE LA RUE', 'ARTS DE LA RUE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (5, 'MUSIQUES ACTUELLES', 'MUSIQUES ACTUELLES');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (6, 'PLURIDISCIPLINAIRE MUSIQUE', 'PLURIDISCIPLINAIRE MUSIQUE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (7, 'MUSIQUES ACTUELLES', 'JAZZ, BLUES ET MUSIQUES IMPROVISÉES');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (8, 'MUSIQUES CLASSIQUES', 'MUSIQUES CLASSIQUES');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (9, 'MUSIQUES ACTUELLES', 'CHANSON');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (10, 'DIVERS SPECTACLE VIVANT', 'HUMOUR');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (11, 'MUSIQUES CLASSIQUES', 'BAROQUE ET ANCIEN');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (12, 'LIVRE ET LITTÉRATURE', 'BANDE DESSINÉE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (13, 'TRANSDISCIPLINAIRE', 'CULTURES D''AFRIQUE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (14, 'TRANSDISCIPLINAIRE', 'ARTS PLATIQUES ET MUSIQUE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (15, 'MUSIQUES CLASSIQUES', 'MUSIQUE DE CHAMBRE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (16, 'ARTS PLASTIQUES ET VISUELS', 'ARTS PLASTIQUES ET VISUELS');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (17, 'DANSE', 'DANSE CONTEMPORAINE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (18, 'CINÉMA ET AUDIOVISUEL', 'CINÉMAS ÉTRANGERS');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (19, 'PLURIDISCIPLINAIRE SPECTACLE VIVANT', 'DANSE ET MUSIQUE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (20, 'PLURIDISCIPLINAIRE SPECTACLE VIVANT', 'JEUNE PUBLIC');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (21, 'DIVERS SPECTACLE VIVANT', 'MARIONNETTES');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (22, 'MUSIQUES CLASSIQUES', 'MUSIQUE CONTEMPORAINE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (23, 'LIVRE ET LITTÉRATURE', 'TRADUCTION');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (24, 'LIVRE ET LITTÉRATURE', 'LIVRE ET LITTÉRATURE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (25, 'CIRQUE ET ARTS DE LA RUE', 'CIRQUE ET ARTS DE LA RUE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (26, 'CIRQUE ET ARTS DE LA RUE', 'CIRQUE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (27, 'LIVRE ET LITTÉRATURE', 'SCIENCES HUMAINES ET SOCIALES');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (28, 'LIVRE ET LITTÉRATURE', 'LITTÉRATURES ÉTRANGÈRES');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (29, 'DOMAINES DIVERS', 'ARCHITECTURE ET PAYSAGE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (30, 'ARTS PLASTIQUES ET VISUELS', 'PHOTOGRAPHIE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (31, 'ARTS PLASTIQUES ET VISUELS', 'DESIGN');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (32, 'DOMAINES DIVERS', 'HISTOIRE ET PATRIMOINE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (33, 'LIVRE ET LITTÉRATURE', 'POÉSIE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (34, 'LIVRE ET LITTÉRATURE', 'LITTÉRATURE POLICIÈRE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (35, 'CINÉMA ET AUDIOVISUEL', 'FILMS FANTASTIQUE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (36, 'PLURIDISCIPLINAIRE SPECTACLE VIVANT', 'MUSIQUE ET DANSE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (37, 'DANSE', 'DANSES URBAINES');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (38, 'CINÉMA ET AUDIOVISUEL', 'DOCUMENTAIRE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (39, 'TRANSDISCIPLINAIRE', 'CRÉATION NUMÉRIQUE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (40, 'DANSE', 'DANSE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (41, 'CINÉMA ET AUDIOVISUEL', 'AUDIOVISUEL');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (42, 'CINÉMA ET AUDIOVISUEL', 'CINÉMA ET AUDIOVISUEL');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (43, 'LIVRE ET LITTÉRATURE', 'ILLUSTRATION');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (44, 'TRANSDISCIPLINAIRE', 'NATURE ET LITTÉRATURE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (45, 'MUSIQUES CLASSIQUES', 'LYRIQUE ET CHORAL');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (46, 'CINÉMA ET AUDIOVISUEL', 'ENFANCE ET JEUNESSE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (47, 'CINÉMA ET AUDIOVISUEL', 'ANIMATION');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (48, 'TRANSDISCIPLINAIRE', 'POP CULTURE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (49, 'TRANSDISCIPLINAIRE', 'CULTURE HIP HOP');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (50, 'DIVERS SPECTACLE VIVANT', 'CONTE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (51, 'CINÉMA ET AUDIOVISUEL', 'COURTS-MÉTRAGES');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (52, 'PLURIDISCIPLINAIRE SPECTACLE VIVANT', 'DANSES ET MUSIQUES URBAINES');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (53, 'DANSE', 'DANSES DU MONDE ET TRADITIONNELLES');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (54, 'TRANSDISCIPLINAIRE', 'CULTURES ÉLECTRONIQUES');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (55, 'THÉÂTRE', 'THÉÂTRE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (56, 'TRANSDISCIPLINAIRE', 'MUSIQUE ET BANDE DESSINÉE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (57, 'PLURIDISCIPLINAIRE SPECTACLE VIVANT', 'HUMOUR, CONTE, MUSIQUE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (59, 'TRANSDISCIPLINAIRE', 'MUSIQUES, DANSES, CINÉMA, EXPOSITIONS');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (60, 'TRANSDISCIPLINAIRE', 'LIVRE ET CINÉMA');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (61, 'ARTS PLASTIQUES ET VISUELS', 'ART NUMÉRIQUE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (62, 'TRANSDISCIPLINAIRE', 'JEUNE PUBLIC');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (63, 'TRANSDISCIPLINAIRE', 'CULTURE ANDALOUSE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (64, 'DOMAINES DIVERS', 'SCIENCES ET TECHNIQUES');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (65, 'TRANSDISCIPLINAIRE', 'GÉOPOLITIQUE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (66, 'DOMAINES DIVERS', 'JOURNALISME');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (67, 'TRANSDISCIPLINAIRE', 'CINÉMA ET NATURE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (68, 'CINÉMA ET AUDIOVISUEL', 'BANDES ANNONCES');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (69, 'LIVRE ET LITTÉRATURE', 'BIOGRAPHIE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (70, 'DIVERS SPECTACLE VIVANT', 'MAGIE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (71, 'PLURIDISCIPLINAIRE SPECTACLE VIVANT', 'DANSE ET ARTS MULTIPLES');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (72, 'PLURIDISCIPLINAIRE SPECTACLE VIVANT', 'CIRQUE, DANSE, PERFORMANCE, MUSIQUE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (73, 'PLURIDISCIPLINAIRE SPECTACLE VIVANT', 'DANSES ET MUSIQUES DU MONDE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (74, 'PLURIDISCIPLINAIRE SPECTACLE VIVANT', 'MUSIQUES ACTUELLES ET ARTS DE LA RUE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (75, 'THÉÂTRE', 'THÉÂTRE ESPAGNOL');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (76, 'LIVRE ET LITTÉRATURE', 'LIVRE AUDIO');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (77, 'LIVRE ET LITTÉRATURE', 'LIVRE DE JEUNESSE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (78, 'TRANSDISCIPLINAIRE', 'CINÉMA, LITTÉRATURE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (79, 'CINÉMA ET AUDIOVISUEL', 'PATRIMOINE CINÉMATOGRAPHIQUE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (80, 'ARTS PLASTIQUES ET VISUELS', 'MODE ET PHOTOGRAPHIE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (81, 'DOMAINES DIVERS', 'JARDINS');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (82, 'CINÉMA ET AUDIOVISUEL', 'FILM POLICIER');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (83, 'CINÉMA ET AUDIOVISUEL', 'PREMIERS FILMS');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (84, 'THÉÂTRE', 'THÉÂTRE AMATEUR');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (85, 'LIVRE ET LITTÉRATURE', 'ARTS DU CARNET');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (86, 'TRANSDISCIPLINAIRE', 'LITTÉRATURE ET CHANSON');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (87, 'TRANSDISCIPLINAIRE', 'MUSIQUE ET ARTS VISUELS');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (88, 'ARTS PLASTIQUES ET VISUELS', 'STREET ART');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (89, 'TRANSDISCIPLINAIRE', 'LECTURES ET SPECTACLES');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (90, 'TRANSDISCIPLINAIRE', 'THÉÂTRE, MARIONNETTES, OBJETS,MUSIQUE, ARTS PLASTIQUES, VIDÉO');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (91, 'THÉÂTRE', 'JEUNE PUBLIC');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (92, 'TRANSDISCIPLINAIRE', 'ARTS PLASTIQUES ET MUSIQUE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (93, 'MUSIQUES ACTUELLES', 'JEUNE PUBLIC');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (94, 'THÉÂTRE', 'IMPROVISATION THÉATRALE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (95, 'TRANSDISCIPLINAIRE', 'JARDINS ET SPECTACLE VIVANT');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (96, 'TRANSDISCIPLINAIRE', 'SPECTACLE VIVANT, ARTS VISUELS, GOÛT');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (97, 'TRANSDISCIPLINAIRE', 'CINÉMA ET MUSIQUE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (98, 'TRANSDISCIPLINAIRE', 'LECTURE, SPECTACLES');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (99, 'PLURIDISCIPLINAIRE SPECTACLE VIVANT', 'MUSIQUE, CIRQUE, HUMOUR');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (100, 'TRANSDISCIPLINAIRE', 'NATURE ET ARTS PLASTIQUES');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (102, 'PLURIDISCIPLINAIRE MUSIQUE', 'MUSIQUES ÉLECTRO');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (103, 'TRANSDISCIPLINAIRE', 'EXPOSITIONS, CONCERTS');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (104, 'PLURIDISCIPLINAIRE SPECTACLE VIVANT', 'MUSIQUES ET DANSES DU MONDE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (105, 'TRANSDISCIPLINAIRE', 'LIVRE ET VIN');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (106, 'TRANSDISCIPLINAIRE', 'ART URBAIN, ART CONTEMPORAIN, MUSIQUES ACTUELLES.');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (107, 'TRANSDISCIPLINAIRE', 'CULTURES URBAINES');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (110, 'TRANSDISCIPLINAIRE', 'SPECTACLE VIVANT, ARTS VISUELS, ARTS PLASTIQUES ET CINÉMA');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (111, 'TRANSDISCIPLINAIRE', 'LIVRE ET ARTS VISUELS');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (112, 'TRANSDISCIPLINAIRE', 'CINÉMA, MUSIQUE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (113, 'TRANSDISCIPLINAIRE', 'LITTÉRATURE ET SPECTACLE VIVANT');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (114, 'TRANSDISCIPLINAIRE', 'MUSIQUE ET CUISINE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (115, 'LIVRE ET LITTÉRATURE', 'SCIENCE FICTION');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (116, 'TRANSDISCIPLINAIRE', 'LITTÉRATURE ET JAZZ');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (118, 'TRANSDISCIPLINAIRE', 'SCIENCE FICTION');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (119, 'TRANSDISCIPLINAIRE', 'LITTÉRATURE ET MUSIQUE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (120, 'DIVERS SPECTACLE VIVANT', 'MIME');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (121, 'TRANSDISCIPLINAIRE', 'CULTURES AFRICAINES');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (122, 'MUSIQUES ACTUELLES', 'ELECTRO');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (123, 'TRANSDISCIPLINAIRE', 'MUSIQUE ET LITTÉRATURE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (124, 'TRANSDISCIPLINAIRE', 'SPORT ET MUSIQUES ACTUELLES');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (125, 'TRANSDISCIPLINAIRE', 'MUSIQUES ET ARTS VISUELS');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (126, 'TRANSDISCIPLINAIRE', 'ARTS ET  CULTURES DU PROCHE-ORIENT');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (127, 'TRANSDISCIPLINAIRE', 'EXPOSITIONS, MUSIQUES ACTUELLES');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (128, 'PLURIDISCIPLINAIRE SPECTACLE VIVANT', 'MUSIQUES ET ARTS DE LA RUE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (129, 'TRANSDISCIPLINAIRE', 'CULTURES NORDIQUES');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (131, 'LIVRE ET LITTÉRATURE', 'ECRITURES');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (132, 'TRANSDISCIPLINAIRE', 'THÉÂTRE ET LECTURE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (133, 'TRANSDISCIPLINAIRE', 'SPECTACLE VIVANT ET ARTS DE LA TABLE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (134, 'TRANSDISCIPLINAIRE', 'VIN ET MUSIQUE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (135, 'LIVRE ET LITTÉRATURE', 'LIVRE HISTORIQUE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (136, 'LIVRE ET LITTÉRATURE', 'REVUES');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (137, 'LIVRE ET LITTÉRATURE', 'LIVRE DE MONTAGNE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (138, 'TRANSDISCIPLINAIRE', 'LIVRE ANCIEN');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (139, 'LIVRE ET LITTÉRATURE', 'POCHE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (140, 'TRANSDISCIPLINAIRE', 'MUSIQUE ET ARTS PLASTIQUES');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (141, 'DANSE', 'SWING');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (142, 'TRANSDISCIPLINAIRE', 'MUSIQUE, THÉÂTRE, CINÉMA, GASTRONOMIE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (143, 'TRANSDISCIPLINAIRE', 'THÉÂTRE, POÉSIE, MUSIQUE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (144, 'TRANSDISCIPLINAIRE', 'THÉÂTRE ET LITTÉRATURE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (145, 'PLURIDISCIPLINAIRE SPECTACLE VIVANT', 'CULTURES URBAINES');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (146, 'TRANSDISCIPLINAIRE', 'MUSIQUE, SPORT ET ÉCOLOGIE');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (147, 'TRANSDISCIPLINAIRE', 'MUSIQUES ACTUELLES ET VINS NATURELS');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (148, 'TRANSDISCIPLINAIRE', 'MUSIQUE ET MOTO');
INSERT INTO domaine (id_domaine, nom_domaine, nom_sous_domaine) VALUES (149, 'TRANSDISCIPLINAIRE', 'MOTO ET MUSIQUE');
