CREATE OR REPLACE PROCEDURE procedure_delete_covoiturage_by_panier_etape(
    ID_PANIER IN NUMBER,
    NB_PLACES_LIBEREES OUT NUMBER,
    ID_FESTIVAL OUT NUMBER
)
AS
    id_covoiturage NUMBER :=0;
    nb_dispo_covoiturage NUMBER :=0;
BEGIN
    SELECT
        SUM(PE.NB_PLACE_OCCUPPE) INTO NB_PLACES_LIBEREES,
        C.NB_PLACE_DISPO INTO NB_DISPO_COVOITURAGE,
        C.ID_COVOITURAGE INTO ID_COVOITURAGE,
        C.ID_FESTIVAL INTO ID_FESTIVAL
    FROM PANIER_ETAPE PE
    JOIN ETAPE E ON E.ID_ETAPE = PE.ID_ETAPE
    JOIN COVOITURAGE C ON C.ID_COVOITURAGE = E.ID_COVOITURAGE
    WHERE PE.ID_PANIER = ID_PANIER;

    IF NB_PLACES_LIBEREES < 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Le nombre de places libérées ne peut pas être négatif');
    END IF;

    UPDATE COVOITURAGE SET NB_PLACE_DISPO = NB_PLACE_DISPO + NB_PLACES_LIBEREES WHERE ID_COVOITURAGE = ID_COVOITURAGE;
END;