DROP TABLE COMMUNE CASCADE CONSTRAINTS;
DROP TABLE DEPARTEMENT CASCADE CONSTRAINTS;
DROP TABLE LIEU CASCADE CONSTRAINTS;
DROP TABLE DOMAIN CASCADE CONSTRAINTS;
DROP TABLE ETAPE CASCADE CONSTRAINTS;
DROP TABLE FESTIVAL CASCADE CONSTRAINTS;
DROP TABLE PANIER CASCADE CONSTRAINTS;
DROP TABLE PANIER_ETAPE CASCADE CONSTRAINTS;