CREATE OR REPLACE PROCEDURE procedure_update_covoiturage_by_panier_etape(
       ID_PANIER IN NUMBER,
       NB_PRISES OUT NUMBER,
       ID_FESTIVAL OUT NUMBER
)
AS
       id_covoiturage NUMBER DEFAULT 0;
       nb_dispo_covoiturage NUMBER DEFAULT 0;
BEGIN
    SELECT
        SUM(PE.NB_PLACE_OCCUPPE) INTO NB_PRISES,
        C.NB_PLACE_DISPO INTO NB_DISPO_COVOITURAGE,
        C.ID_COVOITURAGE INTO ID_COVOITURAGE,
        C.ID_FESTIVAL INTO ID_FESTIVAL
    FROM PANIER_ETAPE PE
    JOIN ETAPE E ON E.ID_ETAPE = PE.ID_ETAPE
    JOIN COVOITURAGE C ON C.ID_COVOITURAGE = E.ID_COVOITURAGE
    WHERE PE.ID_PANIER = ID_PANIER;

    IF NB_DISPO_COVOITURAGE = 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Le covoiturage n a plus de places disponibles');
    END IF;

    IF NB_PRISES > NB_DISPO_COVOITURAGE THEN
        RAISE_APPLICATION_ERROR(-20002, 'Le nombre de places prises est supérieur au nombre de places disponibles');
    END IF;
    UPDATE COVOITURAGE SET NB_PLACE_DISPO = NB_PLACE_DISPO - NB_PRISES WHERE ID_COVOITURAGE = ID_COVOITURAGE;
END;
/